### ISSUE TITLE
Add health enpoint for REST API

### ISSUE THREAD

**Issue by blankdots** [CSCfi/fairdata-metax#6]
Is there a possibility to add a health endpoint that other services can query and check if the API is ok, down or any other status ?

**Comment by EarthModule** [comment]
Hi! There already is a undocumented health check endpoint at /watchman/ and /watchman/ping/ api urls. This was deployed on the last production update, but unfortunately nginx configuration was overlooked, as the health check endpoint needs to be added to its proxy pass list. This will be addressed on next production update on 2022/10/04. Currently, nginx will redirect the requests to health check endpoint to default 404, that is the docs page.

**Comment by blankdots** [comment]
ok super, thx, what is the expected response in case of success and failure ?

**Comment by EarthModule** [comment]
The expected json response from METAX_URL/watchman/ would be
```
{
	"databases": [
		{
			"default": {
				"ok": true
			}
		}
	],
	"elasticsearch": [
		{
			"index: reference_data": {
				"ok": true
			}
		},
		{
			"index: organization_data": {
				"ok": true
			}
		}
	],
	"storage": {
		"ok": true
	},
	"redis": [
		{
			"key: reference_data": {
				"ok": true
			}
		}
	],
	"caches": [
		{
			"default": {
				"ok": true
			}
		}
	]
}
```

**Comment by EarthModule** [comment]
/watchman/ping/ will just responde "pong" (content-type: text/plain)

**Comment by EarthModule** [comment]
metax-test now has a working health check endpoint. Will close this issue.
